# world-service/k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-deployment
  labels:
    app: world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
      - name: hello
        image: dockerdhruvil/worldservice
        ports:
        - containerPort: 3001
